# Generated by Django 4.1.7 on 2023-04-11 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_review_stars_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='stars',
            new_name='rating',
        ),
    ]
